### ISSUE TITLE
UI/UX compared to pomotroid

### ISSUE THREAD

**Issue by Bad3r** [vjousse/pomodorolm#65]
Hello,
I have been using the app lately as an alternative Pomotroid but two UI-related limitations pushed me to switch back. So I thought it might be worth it to add my feedback. Please note that I do appreciate someone taking the time to work on such an amazing project. 

1. Themeing support. pomotroid has a great builtin theming support where I am able to use the same theme as I use on the rest of apps on my OS (Nord Theme)
![image](https://github.com/user-attachments/assets/c95f5585-0490-4650-b06b-1026c823d8fa)

![image](https://github.com/user-attachments/assets/83b7b613-0e62-4b9d-b8b4-7118b545aadf)
2. UI scaling differ from pomotroid
![image](https://github.com/user-attachments/assets/85dda975-4784-4f45-bf3f-5842f1562780)
![image](https://github.com/user-attachments/assets/ec013ede-83cf-4059-9be6-1abbc520b624)

N.2 is hard to descibe. It can be both larger and smaller at times. I use a tiling window manager (i3wm) and usually prefer to have the window as small as in the screenshots and pomotroid seems to scale better.

Example of it being larger:
![image](https://github.com/user-attachments/assets/cfb32f68-3861-42df-9d4b-b89f982b0a03)

it does seem to handle vertical scaling better than pomotroid but I prefer the way pomotroid scales.

**Comment by vjousse** [comment]
Thanks a lot for taking the time to give such useful feedback!

Regarding theming support this is something I will add for sure. I have created the related issue here: https://github.com/vjousse/pomodorolm/issues/66 (I was wondering if it was a feature that someone may use, I now have an answer ;) )

Regarding the scaling, it is something that I have implemented quite recently here https://github.com/vjousse/pomodorolm/pull/46 due to a feature request in pomotroid https://github.com/Splode/pomotroid/pull/238
Pomodorolm is able to scroll proportionally smaller and larger but for it to happen it needs to have the required space in both directions. That's why in your example it's not taking the space at the bottom: there is not enough space on the right. I will check if I can do something about it. I'm tracking it here: https://github.com/vjousse/pomodorolm/issues/67

Anyway, thanks A LOT for your report, it's very appreciated!

**Comment by Bad3r** [comment]
@vjousse thank you for the detailed response. I look forward to the theming support. I just love more theme a lot and it makes using the app so much more visually appealing to me. 

Regarding calling it would be cool if there is a config option for it but I understand if it's not worth it. It's not a big deal anyway.

**Comment by Bad3r** [comment]
> @Bad3r I've released a new version 0.1.5 with theming support. If you don't mind, could you give it a try and tell me if there is anything wrong with it?

Sorry for the late reply! just noticed this. I have been using it and it works great! thank you.
